apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-psd8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-psd8
    app.kubernetes.io/part-of: tkrw-pr714-0075-0048-app
  name: devfile-sample-psd8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-psd8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-psd8
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0048-tenant/tkrw-pr714-0075-0048-app/devfile-sample-psd8@sha256:332cb2b4f442622ec8868fe39ff73ec4fb5012bf5020ddc99ca4de1aeb4dc46e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
